### PR TITLE
Spanish translation

### PR DESCRIPTION
**Pull request by htharker42**
Added the Spanish translations. Let me know what needs adjustment.

### CODE REVIEW

**Comment by wittejm** [comment]
Awesome! I tried running the ttag parser and it ended up exposing some errors which weren't too hard to fix, so I just pushed those up. 

I think the file will get changed again again once my latest PR goes in (no language changes, just code org), but I can take care of that and get all of this merged in. Thank you and Angie!

**Comment by htharker42** [comment]
Great! let me know when everything is up, We want to do a live proofreading.

**Comment by wittejm** [comment]
Ok looking good, I just tagged Kent for a quick review then will merge.

**Review by KentShikama — APPROVED** [review]
Looks good!

**Pull request merged**
